### ISSUE TITLE
Found someways to read the csv file correctly

### ISSUE THREAD

**Issue by chiahuiliu** [Legitblock/voter-visualizations#1]
Hi!
I'm a master student from UT and I'm interested in involving in open source project.
I found some ways to read the csv file correctly.
I'm happy to join the project and have some contribution.
Would you mind I issue a pull request so that I can share my solution with you?

Thanks!
Best,
ChiaHui

**Comment by joshuacox** [comment]
you bet!  We would like to welcome you to our organization.  Generally we are trying to make the openAustin meetups in preparation for the Austin Hack4change event this year.

**Comment by chiahuiliu** [comment]
Thanks for giving me the chance to contribute!
I'll make a pull request for how I read the data and I'll keep working on the visualization/analysis of the data.
Actually I found this project via Open Austin. 👍

**Comment by joshuacox** [comment]
Great!  We look forward to working with you.  Hopefully we'll see you soon at an Open Austin meetup.

**Comment by joshuacox** [comment]
Thanks for the PR.  Closing here, feel free to open more issues!
